//! End-to-end validation of the adaptive prebuffer depth (plans 6.1 + 6.3).
//!
//! The scenarios drive the **real engine** (`spawn_engine_tuned` +
//! `EngineCommand::Start`) on `127.0.0.1` ports in the 417xx range, with
//! packets produced from the **real wire format**
//! (`openay_protocol::encode`) at the realtime pace (~100 pkt/s, 480-sample
//! 10 ms PCM frames) and forwarded through an **in-process `run_proxy`** with
//! a loss profile — the exact production data path minus the sockets' NIC.
//!
//! # Why the test acts as the audio consumer
//!
//! Underruns (the depth controller's trigger) are generated by the RT
//! playback callback, which only exists with the `pipewire` feature (and
//! needs a PipeWire daemon). This headless build has no consumer, so the
//! test takes the SPSC *consumer* role itself via
//! [`EngineHandle::jitter_for_test`]: it pops 480 samples every ~10.5 ms
//! (2% slower than the production rate, so clean streaming builds a small
//! backlog instead of racing the producer) and, exactly like the RT
//! callback, counts a completely dry pop while streaming as one underrun and
//! re-prebuffers. The bursty proxy then genuinely produces the holes that
//! starve the consumer — so the underruns that drive the controller come
//! from real burst loss on the real wire, not from a synthetic counter.
//!
//! With shrunk [`DepthParams`] (600 ms decay window instead of 60 s) the
//! whole rise/decay cycle fits the test budget; assertions are deadline
//! polls, never sleep-exact.
//!
//! These tests are gated on `not(feature = "pipewire")`: with PipeWire the
//! RT callback is the consumer, and a second consumer would violate the
//! jitter buffer's SPSC protocol.

#![cfg(not(feature = "pipewire"))]

use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::sync::atomic::{AtomicBool, AtomicU16, Ordering};
use std::sync::Arc;
use std::time::Duration;

use openay_jitter::DepthParams;
use openay_protocol::{encode, Packet, PayloadType};
use openay_proxy::{Profile, ProxyConfig};
use openay_server::{
    spawn_engine_tuned, CodecMode, EngineCommand, EngineConfig, Transport,
};
use tokio::net::UdpSocket;

/// Shrunk controller timings: +2 ms per underrun, one 600 ms clean window
/// earns −1 ms (real production: 60 s windows — that is why the default
/// 60 s cannot be validated in a sub-minute test).
const SHRUNK_PARAMS: DepthParams = DepthParams {
    rise_ms: 2.0,
    decay_window: Duration::from_millis(600),
    decay_step_ms: 1.0,
};

/// Base (configured) depth for the scenarios, within the 5..=20 clamp.
const BASE_MS: f32 = 10.0;
/// Samples per 10 ms frame at 48 kHz — the phone's frame size.
const FRAME_SAMPLES: usize = 480;
/// Producer pacing: ~100 pkt/s.
const PACKET_INTERVAL: Duration = Duration::from_millis(10);
/// Consumer pacing: 480 samples per 10.5 ms ~= 45.7 k samples/s, 2% under
/// the production rate, so a clean stream builds a small backlog instead of
/// racing the producer into marginal dry pops.
const CONSUMER_INTERVAL: Duration = Duration::from_micros(10_500);
/// The simulated consumer's prebuffer latch (samples): it waits until at
/// least this much audio is buffered before streaming starts. Two frames —
/// enough slack that a scheduler hiccup between the producer's 10 ms wake
/// and the consumer's 10.5 ms wake cannot cause a *phantom* underrun (a
/// completely dry pop with zero packets dropped), while real burst holes
/// (hundreds of ms) still starve it immediately.
const CONSUMER_TARGET: usize = 960;
/// Max frames drained in one catch-up burst (runtime stalls on overloaded
/// CI boxes must not replay an arbitrarily deep history).
const MAX_CATCHUP: u32 = 10;
/// Every phase needs a hard deadline (no unbounded waits, no sleep-exact
/// assertions — CI robustness).
const PHASE_DEADLINE: Duration = Duration::from_secs(12);

/// Monotonic port allocator: each call takes the next 417xx port (probing
/// it), so concurrent tests never collide on the engine/proxy ports.
static NEXT_PORT: AtomicU16 = AtomicU16::new(41_700);

/// Ask the OS for a free UDP port inside the 417xx range, then release it
/// (the engine/proxy binds it next; no race in practice).
fn free_port_417xx() -> u16 {
    for _ in 0..100 {
        let p = NEXT_PORT.fetch_add(1, Ordering::Relaxed);
        if std::net::UdpSocket::bind(SocketAddr::new(Ipv4Addr::LOCALHOST.into(), p)).is_ok() {
            return p;
        }
    }
    panic!("no free port in the 41700..41800 range");
}

/// One 10 ms PCM frame (480 s16le samples, 440 Hz sine at 0.8 FS), encoded
/// to the real wire format with `openay_protocol::encode`.
fn wire_frame(seq: u16) -> Vec<u8> {
    let mut samples = Vec::with_capacity(FRAME_SAMPLES * 2);
    for i in 0..FRAME_SAMPLES {
        let t = (seq as f64 * FRAME_SAMPLES as f64 + i as f64) / 48_000.0;
        let s = (0.8 * 32_767.0 * (2.0 * std::f64::consts::PI * 440.0 * t).sin()) as i16;
        samples.extend_from_slice(&s.to_le_bytes());
    }
    encode(&Packet {
        kind: PayloadType::Pcm,
        seq,
        payload: samples,
    })
}

/// Send `count` frames at ~100 pkt/s into `listen` (the proxy's socket).
/// Stops early when `stop` is set. Returns when done; the receiver side is
/// expected to keep consuming after the sender stops.
async fn send_stream(listen: SocketAddr, count: u16, stop: Arc<AtomicBool>) {
    let sock = UdpSocket::bind((Ipv4Addr::LOCALHOST, 0))
        .await
        .expect("bind sender socket");
    let mut next = tokio::time::Instant::now() + PACKET_INTERVAL;
    for seq in 0..count {
        if stop.load(Ordering::Relaxed) {
            break;
        }
        sock.send_to(&wire_frame(seq), listen)
            .await
            .expect("send frame");
        next += PACKET_INTERVAL;
        tokio::time::sleep_until(next).await;
    }
}

/// The SPSC consumer (headless stand-in for the PipeWire RT callback): pop
/// 480 samples every ~10.5 ms; a completely dry pop while streaming counts
/// one underrun and re-prebuffers (`note_underrun` + latch clear), partial
/// pops are normal and keep streaming — same latch semantics as the RT
/// callback in `pw.rs`.
///
/// If the schedule falls behind (a stalled wake on an overloaded CI box),
/// the consumer drains one frame per missed interval up to [`MAX_CATCHUP`]
/// frames — the async equivalent of back-to-back graph pulls — so a pause
/// cannot starve the underrun generation the scenario depends on.
async fn consumer(jitter: Arc<openay_jitter::JitterBuffer>, stop: Arc<AtomicBool>) -> u64 {
    let mut streaming = false;
    let mut buf = [0.0f32; FRAME_SAMPLES];
    let mut next = tokio::time::Instant::now() + CONSUMER_INTERVAL;
    let mut underruns_observed = 0u64;
    loop {
        if stop.load(Ordering::Relaxed) {
            return underruns_observed;
        }
        let now = tokio::time::Instant::now();
        if now < next {
            tokio::time::sleep_until(next).await;
            continue;
        }
        // Catch-up accounting: one frame per fully elapsed interval.
        let mut due = 0u32;
        while next <= now && due < MAX_CATCHUP {
            next += CONSUMER_INTERVAL;
            due += 1;
        }
        if due == MAX_CATCHUP {
            // Fell behind by more than the cap: drop the stale schedule and
            // resume at the wall clock, never replaying old history.
            next = now + CONSUMER_INTERVAL;
        }
        let mut drained = 0u32;
        while drained < due {
            if stop.load(Ordering::Relaxed) {
                return underruns_observed;
            }
            if streaming || jitter.available() >= CONSUMER_TARGET {
                streaming = true;
                let written = jitter.pop(&mut buf);
                if written == 0 && streaming {
                    jitter.note_underrun();
                    underruns_observed += 1;
                    streaming = false;
                    break; // underrun: stop draining, re-prebuffer
                }
            } else {
                break; // still prebuffering
            }
            drained += 1;
        }
    }
}

/// Seed chosen deterministically so the burst profile's first ~200
/// decisions contain the long bad-state run (packets ~50..80, a 310 ms
/// hole): with this seed the drop sequence is 35 drops in 400 packets with
/// a 31-packet consecutive run — the burstiness the scenario needs, and
/// fully reproducible.
const BURST_SEED: u64 = 0x1;

/// Spawn an in-process lossy proxy and return a quit flag for it.
fn start_proxy(
    listen: SocketAddr,
    forward: SocketAddr,
    profile: Profile,
) -> (Arc<AtomicBool>, tokio::task::JoinHandle<openay_proxy::ProxyStats>) {
    let quit = Arc::new(AtomicBool::new(false));
    let handle = tokio::spawn({
        let quit = quit.clone();
        async move {
            openay_proxy::run_proxy(
                ProxyConfig::new(listen, forward, profile).with_seed(BURST_SEED),
                quit,
            )
            .await
            .expect("proxy must run")
        }
    });
    (quit, handle)
}

/// Poll `status()` until `pred` holds or the deadline elapses. Never
/// sleep-exact: sampling every 100 ms until the deadline.
fn wait_status(
    handle: &openay_server::EngineHandle,
    deadline: Duration,
    mut pred: impl FnMut(&openay_server::EngineStatus) -> bool,
) -> bool {
    let t0 = std::time::Instant::now();
    while t0.elapsed() < deadline {
        let s = handle.status();
        if pred(&s) {
            return true;
        }
        std::thread::sleep(Duration::from_millis(100));
    }
    false
}

/// Scenario 1 — **Rise**: bursty loss (≈9 % mean, runs of ~10 drops) through
/// the proxy starves the consumer, whose dry pops raise the jitter depth.
/// Assert the engine's live `effective_target_ms` climbs above the
/// configured base within a deadline-bounded poll, and that the rise is
/// driven by real underruns on real packets.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn adaptive_depth_rises_under_burst_loss() {
    let engine_port = free_port_417xx();
    let proxy_port = free_port_417xx();
    assert_ne!(engine_port, proxy_port, "distinct ports per scenario");

    let config = EngineConfig {
        transport: Transport::Udp,
        bind: IpAddr::V4(Ipv4Addr::LOCALHOST),
        port: engine_port,
        codec: CodecMode::Auto,
        target_ms: BASE_MS,
        capacity_ms: 100.0,
    };
    let handle = spawn_engine_tuned(Some(config), SHRUNK_PARAMS);
    handle
        .cmd()
        .send(EngineCommand::Start(config))
        .await
        .expect("send Start");
    assert!(
        wait_status(&handle, Duration::from_secs(5), |s| s.running),
        "engine must reach the running state"
    );
    assert_eq!(
        handle.status().effective_target_ms, BASE_MS,
        "a fresh run starts at the configured target"
    );

    // The engine's jitter buffer now exists; the test takes the consumer role.
    let jitter = handle
        .jitter_for_test()
        .expect("jitter buffer must exist while running");

    let engine_addr: SocketAddr = SocketAddr::new(Ipv4Addr::LOCALHOST.into(), engine_port);
    let proxy_addr = SocketAddr::new(Ipv4Addr::LOCALHOST.into(), proxy_port);
    let (proxy_quit, proxy_task) = start_proxy(proxy_addr, engine_addr, Profile::Burst);

    let cons_stop = Arc::new(AtomicBool::new(false));
    let consumer_task = tokio::spawn(consumer(jitter.clone(), cons_stop.clone()));

    // ~600 frames = 6 s of audio at the phone's realtime pace. The seeded
    // burst profile's 27-packet hole spans packets ~53..79 (t ≈ 0.5–0.8 s),
    // long after the sequence tracker has baselined on delivered seq 0, so
    // the hole registers as real loss.
    let producer_task = tokio::spawn(send_stream(proxy_addr, 600, Arc::new(AtomicBool::new(false))));

    // One combined wait: the rise must coincide with mid-stream evidence
    // that actual loss reached the engine. Polling for all conditions
    // together removes any ordering race between the depth controller's
    // 200 ms cadence and the ingest counters (an early underrun alone does
    // not prove loss — it must be accompanied by a tracked gap).
    assert!(
        wait_status(&handle, PHASE_DEADLINE, |s| {
            s.effective_target_ms > BASE_MS + 0.01
                && s.received > 0
                && s.lost > 0
                && s.underruns > 0
        }),
        "burst loss must starve the consumer (underruns), register as lost \
         packets, and raise effective_target_ms above the configured base, \
         status = {:?}",
        handle.status()
    );

    let s = handle.status();
    assert!(s.underruns > 0, "the rise must be driven by underruns, got {}", s.underruns);
    assert!(s.received > 0, "packets must arrive through the proxy, got {}", s.received);
    assert!(s.lost > 0, "burst profile must actually lose packets, got {}", s.lost);
    assert!(
        s.effective_target_ms > BASE_MS,
        "post-condition recheck: target {} must stay above the base",
        s.effective_target_ms
    );

    // Clean shutdown: stop the consumer, producer, proxy, engine.
    cons_stop.store(true, Ordering::Relaxed);
    let _ = producer_task.await;
    let _ = consumer_task.await;
    proxy_quit.store(true, Ordering::Relaxed);
    let _ = proxy_task.await;
    handle.cmd().send(EngineCommand::Stop).await.expect("send Stop");
    assert!(
        wait_status(&handle, Duration::from_secs(5), |s| !s.running),
        "engine must stop cleanly"
    );
}

/// Scenario 2 — **Decay**: after burst loss has raised the target well above
/// the base, switching to a clean stream stops the underruns; each fully
/// elapsed clean window (shrunk to 600 ms) must lower the target by exactly
/// one step back toward the base. The engine keeps running across the
/// switch ("continue clean streaming" — the per-pipeline controller survives
/// the loss profile change).
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn adaptive_depth_decays_stepwise_on_clean_stream() {
    let engine_port = free_port_417xx();
    let burst_proxy_port = free_port_417xx();
    let clean_proxy_port = free_port_417xx();
    assert_ne!(engine_port, burst_proxy_port);
    assert_ne!(engine_port, clean_proxy_port);
    assert_ne!(burst_proxy_port, clean_proxy_port);

    let config = EngineConfig {
        transport: Transport::Udp,
        bind: IpAddr::V4(Ipv4Addr::LOCALHOST),
        port: engine_port,
        codec: CodecMode::Auto,
        target_ms: BASE_MS,
        capacity_ms: 100.0,
    };
    let handle = spawn_engine_tuned(Some(config), SHRUNK_PARAMS);
    handle
        .cmd()
        .send(EngineCommand::Start(config))
        .await
        .expect("send Start");
    assert!(
        wait_status(&handle, Duration::from_secs(5), |s| s.running),
        "engine must reach the running state"
    );

    let jitter = handle
        .jitter_for_test()
        .expect("jitter buffer must exist while running");
    let engine_addr: SocketAddr = SocketAddr::new(Ipv4Addr::LOCALHOST.into(), engine_port);

    let cons_stop = Arc::new(AtomicBool::new(false));
    let consumer_task = tokio::spawn(consumer(jitter.clone(), cons_stop.clone()));

    // Phase 1 (burst): raise the target above the base. Under the shrunk
    // 600 ms window the controller may start decaying between underruns, so
    // this phase only needs a *rise* (any single underrun gives +2 ms); the
    // stepwise relaxation is asserted in the clean phase below.
    let burst_addr = SocketAddr::new(Ipv4Addr::LOCALHOST.into(), burst_proxy_port);
    let (burst_proxy_quit, burst_proxy_task) = start_proxy(burst_addr, engine_addr, Profile::Burst);
    let burst_producer = tokio::spawn(send_stream(burst_addr, 200, Arc::new(AtomicBool::new(false))));
    let _ = burst_producer.await;
    assert!(
        wait_status(&handle, PHASE_DEADLINE, |s| {
            s.effective_target_ms > BASE_MS + 0.01
        }),
        "the burst phase must raise the target above the base, status = {:?}",
        handle.status()
    );
    burst_proxy_quit.store(true, Ordering::Relaxed);
    let _ = burst_proxy_task.await;
    // Drain the burst's delayed holes: the underrun counter is still
    // allowed to tick here — the decay baseline below re-baselines on it.
    tokio::time::sleep(Duration::from_millis(300)).await;

    // Phase 2 (clean): the SAME engine run keeps streaming, but the proxy
    // now forwards everything. Underruns stop, so the window accrues and the
    // target must step down by exactly 1 ms per 600 ms window to the base.
    let clean_addr = SocketAddr::new(Ipv4Addr::LOCALHOST.into(), clean_proxy_port);
    let (clean_proxy_quit, clean_proxy_task) = start_proxy(clean_addr, engine_addr, Profile::Clean);
    let clean_producer =
        tokio::spawn(send_stream(clean_addr, 450, Arc::new(AtomicBool::new(false))));

    let deadline = std::time::Instant::now() + PHASE_DEADLINE;
    let mut last_logged_target = f32::NAN;
    let mut prev_target = f32::NAN;
    let mut step_count = 0u32;
    let mut underrun_baseline = handle.status().underruns;
    let mut reached_base = false;
    while deadline > std::time::Instant::now() {
        let s = handle.status();
        // A late underrun (burst residue) restarts the clean window: the
        // stepwise tracking re-baselines from the current target.
        if s.underruns > underrun_baseline {
            underrun_baseline = s.underruns;
            prev_target = s.effective_target_ms;
            std::thread::sleep(Duration::from_millis(100));
            continue;
        }
        let t = s.effective_target_ms;
        if t < prev_target {
            assert!(
                (prev_target - t - 1.0).abs() < 0.05,
                "decay must step exactly 1 ms per clean window, saw {prev_target} -> {t}"
            );
            last_logged_target = t;
            step_count += 1;
        }
        prev_target = t;
        if (t - BASE_MS).abs() < 0.01 {
            reached_base = true;
            break;
        }
        std::thread::sleep(Duration::from_millis(100));
    }
    assert!(
        reached_base,
        "clean streaming must decay the target back to the {BASE_MS} ms base \
         (last observed {last_logged_target} after {step_count} steps), status = {:?}",
        handle.status()
    );
    assert!(
        step_count >= 2,
        "decay must be stepwise (multiple −1 ms windows), saw {step_count} steps"
    );

    // Engines hold the pipeline until explicitly stopped; shut down cleanly.
    let _ = clean_producer.await;
    clean_proxy_quit.store(true, Ordering::Relaxed);
    let _ = clean_proxy_task.await;
    cons_stop.store(true, Ordering::Relaxed);
    let _ = consumer_task.await;
    handle.cmd().send(EngineCommand::Stop).await.expect("send Stop");
    assert!(
        wait_status(&handle, Duration::from_secs(5), |s| !s.running),
        "engine must stop cleanly"
    );
}
